### ISSUE TITLE
Request in-cluster support for multiple cluster for server side dashboard.

### ISSUE THREAD

**Issue by jgyy** [headlamp-k8s/headlamp#1076]
Would like to have multi cluster option for headlamp that is hosted within cluster. Currently I am able to configure keycloak oidc to login into my eks cluster.

However there is no such options to have both multi-cluster and oidc auth in the dashboard without having to resort to using client based headlamp which is not what i wanted. Kindly enlighten me if I am wrong about it. Thank You!

**Comment by joaquimrocha** [comment]
@jgyy , I think you are right that we only have single cluster options for OIDC when we are running with the in-cluster option.
If you are able to use several OIDC config in the desktop (I am not sure this works), then maybe you can try creating that kubeconfig and running in-cluster but also providing the -kubeconfig option pointing to that file.

**Comment by jgyy** [comment]
Thanks for your comment, from what I read in the given documentations, OIDC login is not supported in desktop client. Configuring oidc token in kubeconfig is not a viable option as the token from keycloak have an expiry date unlike service account token which is permanent unless changed.

I am building up this application for multiple group of users with different permissions, hence editing kubeconfig and hosting it on the server is not an viable option and difficult to set it up.

**Comment by waldner** [comment]
I also second the request to be able to handle multiple clusters from the in-cluster version of headlamp. It would be a convenient alternative to running the desktop version.

**Comment by Adrianos712** [comment]
Same here, we would like to have a centralized console hosted in a k8s "hub" cluster which can allow all kind of users to access the cluster fleet using OIDC authentication to have their own RBAC on each cluster.

**Comment by Adrianos712** [comment]
I just made it working. Here is a sample of my kubeconfig:
```yaml
  config: |
    apiVersion: v1
    kind: Config
    users:
    - name: oidc
      user:
        auth-provider:
          name: oidc
          config:
            client-id: client-id
            client-secret: client-secret
            idp-issuer-url: https://issuer.example.com
            scope: scope1,scope2
    clusters:
      - cluster:
          server: https://cluster_name.example.com
        name: cluster_name
    contexts:
      - context:
          cluster: cluster_name
          user: oidc
```
