### ISSUE TITLE
Support for best-practices SecurityContext

### ISSUE THREAD

**Issue by sudermanjr** [headlamp-k8s/headlamp#1116]
I am trying to deploy headlamp in a Kubernetes cluster with some specific security requirements. Currently, it seems the Dockerfile does not allow running as a non-root user in a Kubernetes cluster. Additionally, I have not been able to get the readOnlyFilesystem flag to work either.

Adding the security context block to the deployment yaml (for the container spec) results in a crashing container:

Full deployment spec:
```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: headlamp
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:v0.17.0
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
        ports:
        - containerPort: 4466
        securityContext:
          runAsUser: 1200
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 200Mi
          requests:
            cpu: 500m
            memory: 200Mi
        volumeMounts:
          - name: plugins
            mountPath: /headlamp/plugins
      volumes:
        - emptyDir: {}
          name: plugins
      nodeSelector:
        'kubernetes.io/os': linux
```

The logs show:

```
2023/05/01 17:21:42 error creating plugins directory: mkdir /.config: permission denied
2023/05/01 17:21:42 static plugin dir:
2023/05/01 17:21:42 plugins-dir: /headlamp/plugins
2023/05/01 17:21:42 open /headlamp/frontend/index.baseUrl.html: permission denied
```
