### ISSUE TITLE
Headlamp doesn't send apiGroup parameter to the SelfSubjectAccessReview API

### ISSUE THREAD

**Issue by Denis220795** [headlamp-k8s/headlamp#1490]
Hello, I was trying to log into Headlamp using the access token for a user who has RoleBinding to the ClusterRole admin that is restricted with a specific namespace (it means it should have full access to the namespace scoped resources).

After this It was found out that my user cannot edit Deployments and other resources that have apiGroups.

It seems like the issue is because Headlmap doesn't send correct apiGroup parameter when requesting for checking access for the current user:

`{"kind":"SelfSubjectAccessReview","apiVersion":"authorization.k8s.io/v1","spec":{"resourceAttributes":{"verb":"update","name":"my-deployment","namespace":"my-namespace","resource":"deployments"}}}` - this is the current request sent by Headlamp to the kube api server and returns false as cluster role admin allow update only for the deployments that are under the apiGroup "apps":

```
- apiGroups:
  - apps
  resources:
  - daemonsets
  - deployments
  - deployments/rollback
  - deployments/scale
  - replicasets
  - replicasets/scale
  - statefulsets
  - statefulsets/scale
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
```

If I add apiGroups parameter to the permission check request then its working fine:
`{"kind":"SelfSubjectAccessReview","apiVersion":"authorization.k8s.io/v1","spec":{"resourceAttributes":{"verb":"update","name":"my-deployment","namespace":"my-namespace","resource":"deployments","group":"apps"}}}`

So it seems like Headlamp should send this apiGroup parameter to correctly check permissions for the resources that are under apiGroups.
