### ISSUE TITLE
Bypass Token / OIDC authentication

### ISSUE THREAD

**Issue by SquupS** [headlamp-k8s/headlamp#1801]
Is it possible to bypass the built in auth methods in case there are other Auth mechanisms in place that you never the lass have to pass until you reach the headlamp frontend?

**Comment by joaquimrocha** [comment]
Using the token via an SA or OIDC is recommended. However, I guess you can set a client certificate in the kubeconfig if you want to bypass it (but this way of course it is not recommendable to expose your headlamp deployment to strangers).

**Comment by SquupS** [comment]
@joaquimrocha Ok. Thanks for the input. Will try. Will not be exposed to strangers since the ingresses will get removed and only the internal cluster service endpoint of headlamp will get used by another frontend wrapping around.

**Comment by illume** [comment]
Can this issue be closed?

**Comment by heubeck** [comment]
@SquupS could you bypass the auth, and if: how?
having quite a similar setup, reverse-proxy in front handling authentication, so that headlamp should not care at all.

**Comment by qixiaobo** [comment]
How to do with this

**Comment by AzySir** [comment]
+1 here - I have no interest in having auth as I port forward to access it. If someone was in my cluster I'd have a bigger issue. Can set a flag to disable authenticator?

**Comment by joaquimrocha** [comment]
Headlamp tries to use selfsubject rules and other methods from the Kubernetes API to understand if it can reach it. If it fails to do so, it will ask for a token. Are you saying that even with the auth proxy you have, Headlamp still cannot connect and you are seeing the token prompt?

**Comment by jcpunk** [comment]
Is this related? https://github.com/kubernetes-sigs/headlamp/pull/3607

**Comment by mhrcm** [comment]
has anyone found a solution to this? I can think of a pretty janky approach with an initContainer but would prefer to avoid

**Comment by peax-zim** [comment]
would also be interested in this

**Comment by dihmandrake** [comment]
> has anyone found a solution to this? I can think of a pretty janky approach with an initContainer but would prefer to avoid

With a bit more complex deployment file one can workaround the requirement for tokens & use service accounts in k8s.
I use the following deployment and Ingress-level authentication:

Deployment:
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: headlamp-clusterview
    app.kubernetes.io/name: headlamp
  name: headlamp-clusterview
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: headlamp-clusterview
      app.kubernetes.io/name: headlamp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: headlamp-clusterview
        app.kubernetes.io/name: headlamp
    spec:
      volumes:
        - name: kubeconfig-dir
          emptyDir:
            sizeLimit: 1M
        - name: headlamp-frontend   # Headlamp needs to modify files in the frontend
          emptyDir:
            sizeLimit: 64M
        - name: headlamp-tmp
          emptyDir:
            sizeLimit: 64M
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
        fsGroup: 20001
      serviceAccountName: headlamp-clusterview
      automountServiceAccountToken: true
      initContainers:
        - name: kubeconfig-creator
          image: busybox:1.37.0@sha256:d80cd694d3e9467884fcb94b8ca1e20437d8a501096cdf367a5a1918a34fc2fd
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - "ALL"
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsUser: 20001
            runAsGroup: 20001
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: "1"
              memory: 128M
            requests:
              cpu: 10m
              memory: 32M
          volumeMounts:
            - name: kubeconfig-dir
              mountPath: /mnt/kubeconfig
              readOnly: false
          command:
            - "sh"
          args:
            - -eux
            - -c
            - |
              # Default Variables
              NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              TOKEN_PATH="/var/run/secrets/kubernetes.io/serviceaccount/token"
              KUBERNETES_SERVICE_HOST=${KUBERNETES_SERVICE_HOST:-"kubernetes.default.svc"}
              KUBERNETES_SERVICE_PORT=${KUBERNETES_SERVICE_PORT:-"443"}
              CERTIFICATE_AUTHORITY="/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"

              # Create the kubeconfig content
              KUBECONFIG_PATH="/mnt/kubeconfig/kubeconfig"
              {
                  echo "apiVersion: v1"
                  echo "kind: Config"
                  echo "clusters:"
                  echo "- name: default-cluster"
                  echo "  cluster:"
                  echo "    certificate-authority: ${CERTIFICATE_AUTHORITY}"
                  echo "    server: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"
                  echo "contexts:"
                  echo "- name: default-context"
                  echo "  context:"
                  echo "    cluster: default-cluster"
                  echo "    namespace: ${NAMESPACE}"
                  echo "    user: default-user"
                  echo "current-context: default-context"
                  echo "users:"
                  echo "- name: default-user"
                  echo "  user:"
                  echo "    tokenFile: ${TOKEN_PATH}"
              } > "${KUBECONFIG_PATH}"

              # Display the kubeconfig path
              echo "Kubeconfig generated at ${KUBECONFIG_PATH}"
        - name: headlamp-frontend-copy
          image: ghcr.io/headlamp-k8s/headlamp:v0.39.0@sha256:c8c564ffbf088955efa4d08523df1b76e3bc4594efaf85efe9996ab99ebe48b2
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - "ALL"
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 101
            runAsUser: 100
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: "2"
              memory: 256M
            requests:
              cpu: 10m
              memory: 40M
          volumeMounts:
            - name: headlamp-frontend
              mountPath: /mnt/headlamp-frontend
              readOnly: false
          command:
            - "cp"
          args:
            - -r
            - /headlamp/frontend/.
            - /mnt/headlamp-frontend
      containers:
        - name: headlamp
          image: ghcr.io/headlamp-k8s/headlamp:v0.39.0@sha256:c8c564ffbf088955efa4d08523df1b76e3bc4594efaf85efe9996ab99ebe48b2
          imagePullPolicy: IfNotPresent
          args:
            - "-kubeconfig=/mnt/kubeconfig/kubeconfig"
          ports:
            - containerPort: 4466
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 1000m
              memory: 256Mi
            requests:
              cpu: 3m
              memory: 32Mi
          securityContext:
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsGroup: 101
            runAsNonRoot: true
            runAsUser: 100
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - name: kubeconfig-dir
              mountPath: /mnt/kubeconfig
              readOnly: true
            - name: headlamp-frontend
              mountPath: /headlamp/frontend
              readOnly: false   # Headlamp needs to modify files in the frontend during startup
            - name: headlamp-tmp  # Headlamp needs to write around in some files
              mountPath: /tmp
              readOnly: false
``` 

RBAC:
```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: headlamp-clusterview
    app.kubernetes.io/name: headlamp
  name: headlamp-clusterview
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/instance: headlamp-clusterview
    app.kubernetes.io/name: headlamp
  name: headlamp-clusterview
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments/scale
      - statefulsets/scale
      - replicasets/scale
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - autoscaling
    resources:
      - horizontalpodautoscalers
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: headlamp-clusterview
    app.kubernetes.io/name: headlamp
  name: headlamp-clusterview
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: headlamp-clusterview
subjects:
  - kind: ServiceAccount
    name: headlamp-clusterview
```

Admitially, a bit hacky, but it works. Maybe someone finds this useful

**Comment by mhrcm** [comment]
> > has anyone found a solution to this? I can think of a pretty janky approach with an initContainer but would prefer to avoid
> 
> With a bit more complex deployment file one can workaround the requirement for tokens & use service accounts in k8s. I use the following deployment and Ingress-level authentication:


Thanks for sharing. I ended up just removing auth altogether and setting up an authentication proxy in front of the instance - which is fine for our use case, but obviously excludes any potential for real RBAC . If I get some time later this year I will see if I can come up with a more elegant solution.

**Comment by peax-zim** [comment]
Heres my helm values that does this:
```
config:
  inCluster: false 
  extraArgs:
    - "-kubeconfig=/mnt/config/kubeconfig"
initContainers:
  - name: init-kubeconfig
    image: busybox:latest
    command:
      - /bin/sh
      - -c
      - |
        KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        KUBE_CA=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt | base64 | tr -d '\n')
        NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
        
        cat <<EOF > /mnt/config/kubeconfig
        apiVersion: v1
        kind: Config
        clusters:
        - name: default-cluster
          cluster:
            certificate-authority-data: ${KUBE_CA}
            server: https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}
        contexts:
        - name: default-context
          context:
            cluster: default-cluster
            user: headlamp
            namespace: ${NAMESPACE}
        current-context: default-context
        users:
        - name: headlamp
          user:
            token: ${KUBE_TOKEN}
        EOF
    volumeMounts:
      - name: shared-config
        mountPath: /mnt/config
volumeMounts:
  - name: shared-config
    mountPath: /mnt/config
volumes:
  - name: shared-config
    emptyDir: {}
```

**Comment by reitermarkus** [comment]
@peax-zim, is this still working for you?

I added this to my Helm values, but now only an empty page with “No clusters found” is shown.

**Comment by reitermarkus** [comment]
Okay, I am using Flux, which was replacing the variables, so `server` was ending up as `https://:`.

Needed to add

```yaml
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
```

to my `kustomization.yaml`.

**Comment by abelorukov** [comment]
another option is to use:
```
config:
  inCluster: false 
  extraArgs:
    - "-kubeconfig=/etc/headlamp/kubeconfig"
volumes:
  - name: kubeconfig
    configMap:
      name: headlamp-kubeconfig
volumeMounts:
  - name: kubeconfig
    mountPath: /etc/headlamp/kubeconfig
    subPath: kubeconfig
    readOnly: true

extraManifests:
  - |
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: headlamp-kubeconfig
    data:
      kubeconfig: |
        apiVersion: v1
        kind: Config
        clusters:
        - cluster:
            certificate-authority: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
            server: https://kubernetes.default.svc
          name: in-cluster
        contexts:
        - context:
            cluster: in-cluster
            user: headlamp-sa
          name: in-cluster
        current-context: in-cluster
        users:
        - name: headlamp-sa
          user:
            tokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
```
