### ISSUE TITLE
In-cluster deployment looks for a kubeconfig

### ISSUE THREAD

**Issue by rosh-cha** [headlamp-k8s/headlamp#1826]
Trying to deploy headlamp using the kubernetes-headlamp.yaml in to a k8s cluster.
Does the in cluster deployment suppose to look for the kubeconfig?

```
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":305,"time":"2024-03-18T22:51:07Z","message":"Creating Headlamp handler"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":306,"time":"2024-03-18T22:51:07Z","message":"Kubeconfig path: "}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":307,"time":"2024-03-18T22:51:07Z","message":"Static plugin dir: /headlamp/static-plugins"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":308,"time":"2024-03-18T22:51:07Z","message":"Plugins dir: /headlamp/plugins"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":309,"time":"2024-03-18T22:51:07Z","message":"Dynamic clusters support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":310,"time":"2024-03-18T22:51:07Z","message":"Helm support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":311,"time":"2024-03-18T22:51:07Z","message":"Proxy URLs: []"}
{"level":"info","context":"main","clusterURL":"https://10.96.0.1:443","source":"/headlamp/backend/pkg/kubeconfig/kubeconfig.go","line":172,"time":"2024-03-18T22:51:07Z","message":"Proxy setup"}
*** Headlamp Server ***
  API Routers:
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":365,"error":"read /: is a directory","time":"2024-03-18T22:51:07Z","message":"loading kubeconfig"}
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":376,"error":"open /home/headlamp/.config/Headlamp/kubeconfigs/config: no such file or directory","time":"2024-03-18T22:51:07Z","message":"loading dynamic kubeconfig"}
```

**Comment by thomaspetit** [comment]
+1 saw the same error

**Comment by GraysonCAdams** [comment]
Same issue here...

Is in-cluster deployment just straight up broken?

How did you resolve this @rosh-cha  or @thomaspetit ?

**Comment by thomaspetit** [comment]
No, haven't had the time to look into it as I've been quite busy fixing my bootstrap script for my local clusters. Might want to revisit this soon with the latest multi-cluster features that I read about (for in-cluster deployments).

**Comment by dabecow** [comment]
I'm facing the same issue, no luck with deploying according to the https://headlamp.dev/docs/latest/installation/in-cluster/ :(

**Comment by Dunnymeister** [comment]
Same issue here, not sure how to get started...

**Comment by quinhn** [comment]
Same issue with Keycloak OIDC configuration

**Comment by gavin-ob** [comment]
Same issue, I really just want to bypass the OIDC authentication as I already have auth happening via a reverse proxy. Is there anyway to pass kubeconfig in via values.yaml? or if not does anyone know how I might remove the need for auth? Apologies if that makes no sense, I am far from an expert :) it may be that kubeconfig doesn't need passing and I just need to somehow disable the need for OIDC token

**Comment by illume** [comment]
Ah, I didn't think anyone would load kube configs in-cluster.

I think most people won't use a kube config when deploying in cluster? So in the case when Headlamp is running in-cluster (and not as an app) then these should be warning logs and not error logs.

**Comment by yolossn** [comment]
I agree that many wont be using kubeconfigs in the cluster but removing it completely can affect the existing workflows for people so making it available based on a config can be the way to go.

**Comment by Guilamb** [comment]
> FYI, we're currently loading a static kubeconfig file in cluster by mounting onto `/home/headlamp/.config/Headlamp/kubeconfigs/config` a secret holding a kubeconfig file (in our case, we craft it using external secret operator).
> 
> ```yaml
>     volumeMounts:
>       - name: "headlamp-kubeconfig"
>         mountPath: "/home/headlamp/.config/Headlamp/kubeconfigs/"
> 
>     volumes:
>       - name: "headlamp-kubeconfig"
>         secret:
>           secretName: "kubeconfig-vc-crossplane-consumer"
>           mountPath: "/home/headlamp/.config/Headlamp/kubeconfigs/"
> ```
> 
> We still need to test support for multiple kubeconfig files, by passing the [`-kubeconfig` argument](https://github.com/headlamp-k8s/headlamp/blob/e0b66e5eb3a020a03318ac934a94fe9614c6742c/backend/pkg/config/config.go#L157) or the KUBECONFIG env (through helm [values.env](https://github.com/headlamp-k8s/headlamp/blob/101ef9060f833af3e45890f36cf66045d85f3661/charts/headlamp/values.yaml#L90-L94)) with `:` separated paths as documented into https://headlamp.dev/docs/latest/installation/desktop/#use-several-kube-config-files
> 
> /CC @Guilamb

So I've tried using the `KUBECONFIG `environment variable but without success. However, using the` -kubeconfig` flag, which I added in the Helm chart using extraArgs, worked with the `:` separator: ```-kubeconfig=home/headlamp/.config/Headlamp/kubeconfigs/kubeconfig1:home/headlamp/.config/Headlamp/kubeconfigs/kubeconfig2.```

**Comment by meysam81** [comment]
I'm on the latest stable version of the headlamp (`ghcr.io/headlamp-k8s/headlamp:v0.27.0`) and I still see this error.

I fixed it by modifying the following values to the helm `values.yml` file:


```yaml
initContainers:
  - command:
      - /bin/sh
      - "-c"
      - |
        kubectl config set-cluster main --server=https://kubernetes.default.svc --certificate-authority=/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        kubectl config set-credentials main --token=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
        kubectl config set-context main --cluster=main --user=main
        kubectl config use-context main
    env:
      - name: KUBERNETES_SERVICE_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
      - name: KUBERNETES_SERVICE_PORT
        value: "6443"
      - name: KUBECONFIG
        value: /home/headlamp/.config/Headlamp/kubeconfigs/config
    image: bitnami/kubectl:1.32.0
    name: create-kubeconfig
    securityContext:
      capabilities:
        drop:
          - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsGroup: 101
      runAsNonRoot: true
      runAsUser: 100
    volumeMounts:
      - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs
        name: kubeconfig


volumeMounts:
  - mountPath: /home/headlamp/.config/Headlamp/kubeconfigs/config
    name: kubeconfig
    readOnly: true
    subPath: config

volumes:
  - name: kubeconfig
    emptyDir: {}

```
