### ISSUE TITLE
Can't access/display OIDC authentication page

### ISSUE THREAD

**Issue by genseb13011** [headlamp-k8s/headlamp#1849]
Hi,

I'm facing an issue when I try to configure OIDC authentication, more precisaly the OIDC page is never displayed (always token access page).

**Deployment informations**

Helm chart: headlamp from https://headlamp-k8s.github.io/headlamp/
Helm version: 0.19.0

**What I've tried:**

- I've tried to set env variable with:

```
env:
  - name: HEADLAMP_CONFIG_OIDC_CLIENT_ID
    value: "xxxxxxxx"
  - name: HEADLAMP_CONFIG_OIDC_CLIENT_SECRET
    value: "xxxxxxxx"
  - name: HEADLAMP_CONFIG_OIDC_IDP_ISSUER_URL
    value: "xxxxxxxx"
```

- i've tried to set OIDC variable under config.oidc

```
config:
  oidc:
    secret:
      create: true
      name: oidc
    clientID: "xxxxxxxxxxx"
    clientSecret: "xxxxxxxxxxxx"
    issuerURL: "xxxxxxxxxxx"
```

Am I missing something?

Sébastien.
