### ISSUE TITLE
Loading clusters from a KubeConfig file is broken

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#1883]
A user has reported that they couldn't load a cluster from a kubeconfig file from  the UI but could do it via the env var.
I took a look and turns out that since the stateless clusters, we have an exception being raised in the client code since we assume there to be an answer when the cluster is successfully set up but now there is none.

Here is a kubeconfig that illustrates the issue:
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://k8s-api.dev-use1-100.domain.com/
  name: dev-use1-100
contexts:
- context:
    cluster: dev-use1-100
    user: cdenneen-dev-use1-100
  name: cdenneen-dev-use1-100
current-context: cdenneen-dev-use1-100
kind: Config
preferences: {}
users:
- name: cdenneen-dev-use1-100
  user:
    token: REDACTED
```
