### ISSUE TITLE
external auth (exec) not working (azure/kubelogin and aws-iam-authenticator)

### ISSUE THREAD

**Issue by hofq** [headlamp-k8s/headlamp#1885]
I tried connecting to our prod clusters using "azure/kubelogin" and aws-iam-authenticator.

None of these Auth Methods worked.

Is there an eta we can expect exec auth to work? We want to switch from the closed source software lens to headlamp, but this is currently blocking.

**Comment by illume** [comment]
Hi. 

Thanks for writing.

Yeah, we use the k8s APIs rather than kubectl and haven't implemented support for the "[client-go credential plugins](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins)".

As a not-great work around authentication for both AKS and EKS can be done with OIDC. I realize this is probably not suitable however. Because the point of the aws-iam-authenticator is to avoid having to manage separate services. (please correct me if I'm wrong?)

Supporting external auth commands isn't _currently_ on the short term roadmap. But I personally think it's something we should support.


---

### External auth related docs

- [client-go credential plugins](https://kubernetes.io/docs/reference/access-authn-authz/authentication/#client-go-credential-plugins)
- [aws-iam-authenticator](https://github.com/kubernetes-sigs/aws-iam-authenticator)
- [azure/kubelogin](https://github.com/Azure/kubelogin)


```yaml
exec:
    apiVersion: ...
    command: ...
    args: ...
```

### Other related issues:

A number of others have reported here and elsewhere wanting support for external auth commands. 

Here are some of the github issues:

- #1582
- #1341

**Comment by gaeljw** [comment]
I agree this will be a must have for most companies.

**Comment by strowi** [comment]
Would also like for this to work. I'm guessing there are a lot of people using some form of client-side addon (e.g. i am using passman to store the credentials in keychain):

```
- name: rancher
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - keychain
      - user@cluster
      command: kubectl-passman
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
