### ISSUE TITLE
No ingressClassName in helm chart

### ISSUE THREAD

**Issue by gecube** [headlamp-k8s/headlamp#1895]
Good day!

I am trying to install headlamp in test lab env.

I found that there is missing `ingressClassName` in helm chart in ingress definition. It means that there must be present default ingress class name set up in the cluster what is not the default behaviour.

So with naive installation I have:

```
kubectl get ing -A
NAMESPACE   NAME       CLASS    HOSTS                               ADDRESS   PORTS     AGE
headlamp    headlamp   <none>   headlamp.dashboard-test.gecube.eu             80, 443   54s
```

But it should be something like

```
kubectl get ing -A
NAMESPACE   NAME       CLASS    HOSTS                               ADDRESS   PORTS     AGE
headlamp    headlamp   nginx    headlamp.dashboard-test.gecube.eu             80, 443   54s
```

Also I found very counter-intuitive how to fill the `ingress` key in `values.yaml` It has completely different approach than I have seen before - particularly in so well known charts like from `bitnami` or even `minio-operator`...

**Comment by gecube** [comment]
Temporarily fixed with FluxCD helm release patch:

```
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
      version: '0.20.0'
  interval: 1m0s
  values:
    replicaCount: 1
...
    env:
    - name: KUBERNETES_SERVICE_HOST
      value: "kube-oidc-proxy.console.svc.cluster.local."
    - name: KUBERNETES_SERVICE_PORT
      value: "443"
    ingress:
      enabled: true
      hosts:
      - host: headlamp.dashboard-test.gecube.eu
        paths:
        - path: /
          type: Prefix
      tls:
      - secretName: headlamp-tls
        hosts:
          - headlamp.dashboard-test.gecube.eu
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-http01-nginx-issuer
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Ingress
              name: headlamp
            patch: |
              - op: add
                path: /spec/ingressClassName
                value: nginx
          - target:
              kind: Deployment
              name: headlamp
            patch: |
              - op: add
                path: /spec/template/spec/containers/0/args/-
                value: -insecure-ssl
```
