### ISSUE TITLE
Helm chart value treated as a number

### ISSUE THREAD

**Issue by gecube** [headlamp-k8s/headlamp#1896]
Hello!

I am trying to install Headlamp like a helm chart with a custom Kubernetes endpoint.
So I prepared such a values file:

```
...
    env:
    - name: KUBERNETES_SERVICE_HOST
      value: "kube-oidc-proxy.console.svc.cluster.local."
    - name: KUBERNETES_SERVICE_PORT
      value: 443
...
```

and I am getting the next error from FluxCD which is my deployment system:

```
headlamp            	helmrelease/headlamp            	        	False    	False	Helm install failed for release headlamp/headlamp with chart headlamp@0.20.0: 1 error occurred:                                                                                 	
                    	                                	        	         	     		* Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field EnvVar.spec.template.spec.containers.env.value of type string	
                    	                                	        	         	     		*
```

So it's definitely not an issue with the FluxCD itself. Also I want to mention that I can rewrite the values in such a way:

```
...
    env:
    - name: KUBERNETES_SERVICE_HOST
      value: "kube-oidc-proxy.console.svc.cluster.local."
    - name: KUBERNETES_SERVICE_PORT
      value: "443"
...
```

and it looks like that solves the issue, but I am really goind mad and crazy why I need to quote the port number.

So I am kindly asking to think about how to
- workaround this issue
- make better examples and/or documentation for headlamp
