### ISSUE TITLE
Helm chart OIDC config with existing secret not working as expected

### ISSUE THREAD

**Issue by elroy-haw** [headlamp-k8s/headlamp#2022]
I have created a Secret called `headlamp-oidc` outside of Headlamp's Helm chart, but specifying it in my values.yaml as shown below doesn't configure Headlamp's arguments nor environment variables correctly. As such, the application is started without the OIDC configurations.
```yaml
config:
  oidc:
    secret:
      create: false
      name: headlamp-oidc # this OIDC Secret was created outside of the Helm chart
```

I believe the issue is with how the deployment.yaml template is currently defined.
```yaml
env:
  {{- if $oidc.secret.create }}  # this is currently not handling the case where the OIDC Secret was created outside of the Helm chart
  {{- if $oidc.clientID }}
  - name: OIDC_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: {{ $oidc.secret.name }}
        key: clientID
```

Happy to open a PR to fix this if required!

**Comment by elroy-haw** [comment]
Current workaround is to add the OIDC environment variables into values.yaml manually as shown below.
```yaml
env:
  - name: OIDC_CLIENT_ID
    valueFrom:
      secretKeyRef:
        name: headlamp-oidc
        key: clientID
  - name: OIDC_CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: headlamp-oidc
        key: clientSecret
  - name: OIDC_ISSUER_URL
    valueFrom:
      secretKeyRef:
        name: headlamp-oidc
        key: issuerURL
  - name: OIDC_SCOPES
    valueFrom:
      secretKeyRef:
        name: headlamp-oidc
        key: scopes
```

**Comment by knrt10** [comment]
Thank you @elroy-haw for opening the issue, looking into it

**Comment by knrt10** [comment]
@elroy-haw for using external secret you have to use it like this. Can you please try it? Thanks

```value.yaml
# Option 3:
    # @param config.oidc - External OIDC secret configuration
    # If you want to use an external secret for OIDC configuration, enable this option.
    # Provide the name of the secret to use.
    # Example:
    # config:
    #   oidc:
    #     secret:
    #       create: false
    #     externalSecret:
    #       enabled: true
    #       name: headlamp-oidc
```

**Comment by davidfrickert** [comment]
does not work for me, the chart tries to create:

```
          env:
            envFrom:
              - secretRef:
                  name: oidc
```

this is not valid, the correct syntax per kubernetes docs is

```
            envFrom:
              - secretRef:
                  name: oidc
```

(remove env:) 

--> https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/
