### ISSUE TITLE
Error in values.schema.json and values.yaml in ingress section (helm chart)

### ISSUE THREAD

**Issue by BlindB0** [headlamp-k8s/headlamp#2061]
Hi!
values.schema.json have error in ingress section.
For block
```
spec:
  rules:
    - host: "hostname"
      http:
        paths:
          - path: /
            pathType: Prefix
```
values.schema.json looks like:

```
              "paths": {
                "type": "array",
                "items": {
                  "type": "string"
                }
```
But must look like this:
```
              "paths": {
                "type": "array",
                "items": {
                  "type": "object"
                }
```
Because in template ingress.yaml:
```
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .type }}
            backend:
              service:
                name: {{ $fullName }}
                port: 
                  number: {{ $svcPort }}
          {{- end }}
    {{- end }}
```
So, in values.yaml we must also make fix:
```
ingress:
  hosts:
    []
    # - host: chart-example.local
    #   paths:
    #     - path: /
    #       type: ImplementationSpecifichosts
```
