### ISSUE TITLE
Not possible to add multiple cluster with same context

### ISSUE THREAD

**Issue by dark0ni** [headlamp-k8s/headlamp#2236]
Hello,

I found the following bug: when I want to add an additional cluster where the context has the namespace "default" like the first added cluster, it does nothing.  I can't also change the name of the first added cluster from "default" to another name.  

Here is an example:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXXXXXXXXX....
    server: https://XXXXXXXXX.k8s.ondigitalocean.com
  name: clustername-01
contexts:
- context:
    cluster: clustername-01
    namespace: custom-namespace-01-prod
    user: team-xxxxx
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: team-xxxxx
  user:
    client-key-data: XXXXXXXXX....
    token: XXXXXXXXXXX....

```

All my kubeconfig files look the same with different cluster names and providers. Also, the program requires the token to open the cluster, but there are already existing bug tickets for that :)  

Thank you in advance.

**Comment by joaquimrocha** [comment]
Hi @dark0ni . I would like more details:
1. Are you running Headlamp desktop or web?
2. What are the steps you do to reproduce this issue? (it may seem obvious from your description, but I want to make sure we're thinking about the same when I read "adding a cluster")

Also, do you see more clusters/contexts if you add them to the kubeconfig that you know is being loaded?

**Comment by dark0ni** [comment]
Sure

Also i cant remove the cluster anymore


1. I run the Desktop Version on Windows 11 Pro 23H2
2. Steps to reproduce:

1. Add the kubeconfig to headlamp
2. added as "default"
3. try to change name to another name with numeric and - for example "m6-dev"
4. Dont change the cluster name
5. Try to add an additional kubeconfig with default as name
6. No reaction from GUI
7. Try to remove current cluster in the list, also not possible

--> some json parsing error occure in the console

Here additional logs from web console:
```
index-BhWvm8rb.js:849 Unable to parse error json at url: http://localhost:4466/clusters/default/version {err: SyntaxError: Unexpected non-whitespace character after JSON at position 4 (line 1 column 5)} with request data: {signal: AbortSignal, headers: {…}}
clusterRequest @ index-BhWvm8rb.js:849
```

![image](https://github.com/user-attachments/assets/f6c4f574-9918-48cc-a627-032d889b004d)

**Comment by dark0ni** [comment]
when i try JSON.stringify(ke) i get a empty json '{}' as result
a normal print in the console i get returned the request:

![image](https://github.com/user-attachments/assets/1ba155e3-7886-4b58-b613-99f523f1f0bc)

**Comment by joaquimrocha** [comment]
Thanks @dark0ni ! I think this helps a lot. We will investigate and keep you posted.

**Comment by joaquimrocha** [comment]
> This would require us to rethink how we store and handle kubeconfigs. Maybe offer to rename the context name when user tries to add another one? 

Yeah. Or we just append a suffix that we can iterate (1..N).

I think one thing we need to double check is having entries in storage which do not show up in Headlamp. If they aren't shown, why are they stored? ( or vice-versa)

**Comment by sniok** [comment]
> I think one thing we need to double check is having entries in storage which do not show up in Headlamp. If they aren't shown, why are they stored? ( or vice-versa)

Configs are stored in indexeddb, but then when we send them to the backend to the `parseKubeConfig` endpoint, it returns just one

**Comment by knrt10** [comment]
Looked more into the issue, but I want to clarify some of the questions folks are having

` renaming should be local and stored as a context name instead of cluster name`

- We do not rename cluster name we rename context only, that also we add it as a custom extension field. For example when a user renames their cluster (which is actually a context - we do need to clarify these 2 things i.e be able to differentiate context or cluster), this is added to their kubeconfig keeping actual values unchanged
```yaml
- context:
    cluster: test
    extensions:
    - extension:
        creationTimestamp: null
        customName: renametest
      name: headlamp_info
```  

`indexeddb may be simplified to localstorage`

- We had the same conversation before, but it might be lost in PR reviews, we initially implemented localstorage only. But since kubeconfig can be quite big and there is a limit on how much data can we store in localstorage(5mb IIRC) we opted for using indexDB. Since it has the storage capacity of the user's device storage.

I do have found the bug, it is happening how we are storing kubeconfig. Fixing it
