### ISSUE TITLE
Dynamic cluster plugin issue 

### ISSUE THREAD

**Issue by manujayanth** [headlamp-k8s/headlamp#2249]
Hi team,

I have been deployed dynamic cluster plugin through init containers in my cluster.  When I load any kubeconfig file with base64 and choose the cluster to be used. I am getting this issue. 

Note: This issue observed both in local and production environment when deployed with helm charts

![image](https://github.com/user-attachments/assets/a38f351f-4d9b-413c-a190-84fbd9f4ce15)

**Comment by manujayanth** [comment]
FYI  @joaquimrocha

**Comment by joaquimrocha** [comment]
Thank you @manujayanth . We will take a look.

**Comment by knrt10** [comment]
Hi @manujayanth, can you please share how you are using the authentication of the cluster?

You have to use `certificate-authority-data` for server and `client-certificate-data` and `client-key-data` for user authentication. I tried it locally and it is working, can you please share more logs from your helm pod. Thanks

**Comment by manujayanth** [comment]
@knrt10  This is how my kubeconfig looks like:

apiVersion: v1
kind: Config
clusters:
- name: "****"
  cluster:
    server: "***"
    certificate-authority-data: "****"
users:
- name: "****"
  user:
    token: "****"


contexts:
- name: "****"
  context:
    user: "***"
    cluster: "***"


current-context: "***"


Logs: 
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":314,"time":"2024-08-22T06:50:41Z","message":"Helm support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":315,"time":"2024-08-22T06:50:41Z","message":"Proxy URLs: []"}
{"level":"info","context":"main","clusterURL":"https://10.96.0.1:443","source":"/headlamp/backend/pkg/kubeconfig/kubeconfig.go","line":201,"time":"2024-08-22T06:50:41Z","message":"Proxy setup"}
*** Headlamp Server ***
  API Routers:
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":369,"error":"read /: is a directory","time":"2024-08-22T06:50:41Z","message":"loading kubeconfig"}
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":380,"error":"open /home/headlamp/.config/Headlamp/kubeconfigs/config: no such file or directory","time":"2024-08-22T06:50:41Z","message":"loading dynamic kubeconfig"}

**Comment by knrt10** [comment]
Hi @manujayanth thank you for the detailed information. Can you please confirm what authentication method are you using in kubeconfig for users? As I can see it only has token. As I mentioned above it needs client certificate and key data.

**Comment by manujayanth** [comment]
@knrt10 Even tried with client certificate and key data..It doesn’t seem to work.Can you provide ur helm charts if possible

**Comment by knrt10** [comment]
@manujayanth as the logs says 

```
{"level":"error","source":"/headlamp/backend/cmd/stateless.go","line":98,"error":["cluster not found for context: "og-dev-lutl-armjn-01""],"time":"2024-08-22T07:09:25Z","message":"setting up contexts from kubeconfig"}
```
The above logs clearly state there is issue with server authentication, which means `certificate-authority-data` is not present. 
Can you try accessing your cluster from `kubectl` and confirm it is working or not? Thanks

**Comment by manujayanth** [comment]
@knrt10 Thanks for detailed info. Now my kubeconfig contains  certificate-authority-data. Getting this screen now after adding the cluster

![image](https://github.com/user-attachments/assets/f124fefb-fad5-434c-9df3-c1e1470bdd7c)


I don't know why it's asking token after adding kubeconfig file

**Comment by knrt10** [comment]
Can you please check if clustername and context name is same?

**Comment by manujayanth** [comment]
Hi @knrt10 My kubeconfig looks like

 apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ""
    server: ""
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes
current-context: kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: ""
    client-key-data: ""

Error: 
![image](https://github.com/user-attachments/assets/7d7d0a0b-5b91-4c1d-ac41-7b97ff5e502b)

Same kubeconfig works with kubectl command

**Comment by knrt10** [comment]
Hi @manujayanth  Let me paste you the exact steps you can try. I have already built the plugins image you don't need to build it.

- Change your `values.yaml` in charts folder to below. 

<details>
  <summary>Click to expand <strong>values.yaml</strong> </summary>

```yaml
# Default values for headlamp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of desired pods
replicaCount: 1

image:
  # -- Container image registry
  registry: ghcr.io
  # -- Container image name
  repository: headlamp-k8s/headlamp
  # -- Image pull policy. One of Always, Never, IfNotPresent
  pullPolicy: IfNotPresent
  # -- Container image tag, If "" uses appVersion in Chart.yaml
  tag: ""

# -- An optional list of references to secrets in the same namespace to use for pulling any of the images used
imagePullSecrets: []
# -- Overrides the name of the chart
nameOverride: ""
# -- Overrides the full name of the chart
fullnameOverride: ""

# -- An optional list of init containers to be run before the main containers.
initContainers:
- command:
  - /bin/sh
  - -c
  - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
  image: knrt10/headlamp-plugins-test:latest
  imagePullPolicy: IfNotPresent
  name: headlamp-plugins
  volumeMounts:
  - mountPath: /build/plugins
    name: headlamp-plugins

config:
  # -- base url path at which headlamp should run
  baseURL: ""
  oidc:
    # Option 1:
    # @param config.oidc.secret - OIDC secret configuration
    # If you want to use an existing secret, set create to false and provide the name of the secret.
    # If you want to create a new secret, set create to true and provide the name of the secret.
    # Also provide the values for clientID, clientSecret, issuerURL, and scopes.
    # Example:
    # config:
    #   oidc:
    #     secret:
    #       create: true
    #       name: oidc
    secret:
      # -- Generate OIDC secret. If true, will generate a secret using .config.oidc.
      create: true
      # -- Name of the OIDC secret.
      name: oidc

    # Option 2:
    # @param config.oidc - OIDC env configuration
    # If you want to set the OIDC configuration directly, set the following values.
    # Example:
    # config:
    #   oidc:
    #     clientID: "clientID"
    #     clientSecret: "clientSecret"
    #     issuerURL: "issuerURL"
    #     scopes: "scopes"

    # -- OIDC client ID
    clientID: ""
    # -- OIDC client secret
    clientSecret: ""
    # -- OIDC issuer URL
    issuerURL: ""
    # -- OIDC scopes to be used
    scopes: ""

    # Option 3:
    # @param config.oidc - External OIDC secret configuration
    # If you want to use an external secret for OIDC configuration, enable this option.
    # Provide the name of the secret to use.
    # Example:
    # config:
    #   oidc:
    #     secret:
    #       create: false
    #     externalSecret:
    #       enabled: true
    #       name: oidc
    externalSecret:
      enabled: false
      name: ""
  # -- directory to look for plugins
  pluginsDir: "/build/plugins"
  # Extra arguments that can be given to the container. See charts/headlamp/README.md for more information.
  extraArgs:
  - "-enable-dynamic-clusters"

# -- An optional list of environment variables
# env:
#   - name: KUBERNETES_SERVICE_HOST
#     value: "localhost"
#   - name: KUBERNETES_SERVICE_PORT
#     value: "6443"

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.(If not set and create is true, a name is generated using the fullname template)
  name: ""

clusterRoleBinding:
  # -- Specified whether a cluster role binding should be created
  create: true
  # -- Annotations to add to the cluster role binding
  annotations: {}

# -- Annotations to add to the pod
podAnnotations: {}

# -- Headlamp pod's Security Context
podSecurityContext:
  {}
  # fsGroup: 2000

# -- Headlamp containers Security Context
securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  runAsNonRoot: true
  privileged: false
  runAsUser: 100
  runAsGroup: 101

service:
  # -- Kubernetes Service type
  type: ClusterIP
  # -- Kubernetes Service port
  port: 80

# -- Headlamp containers volume mounts
volumeMounts:
- mountPath: /build/plugins
  name: headlamp-plugins

# -- Headlamp pod's volumes
volumes:
- name: headlamp-plugins
  persistentVolumeClaim:
    claimName: headlamp

persistentVolumeClaim:
  # -- Enable Persistent Volume Claim
  enabled: true
  # -- Annotations to add to the persistent volume claim (if enabled)
  annotations:
    {}
  # -- accessModes for the persistent volume claim, eg: ReadWriteOnce, ReadOnlyMany, ReadWriteMany etc.
  accessModes:
  - ReadWriteOnce
  # -- size of the persistent volume claim, eg: 10Gi. Required if enabled is true.
  size: "1Gi"
  # -- storageClassName for the persistent volume claim.
  storageClassName: "headlamp"
  # -- selector for the persistent volume claim.
  selector: {}
  # -- volumeMode for the persistent volume claim, eg: Filesystem, Block.
  volumeMode: ""

ingress:
  # -- Enable ingress controller resource
  enabled: false
  # -- Annotations for Ingress resource
  annotations:
    {}
    # kubernetes.io/tls-acme: "true"

  # -- Ingress class name. replacement for the deprecated "kubernetes.io/ingress.class" annotation
  ingressClassName: ""

  # -- Hostname(s) for the Ingress resource
  # Please refer to https://kubernetes.io/docs/reference/kubernetes-api/service-resources/ingress-v1/#IngressSpec for more information.
  hosts:
    []
    # - host: chart-example.local
    #   paths:
    #   - path: /
    #     type: ImplementationSpecific
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- CPU/Memory resource requests/limits
resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# -- Node labels for pod assignment
nodeSelector: {}

# -- Toleration labels for pod assignment
tolerations: []

# -- Affinity settings for pod assignment
affinity: {}

```

</details>

- install it from headlamp folder `helm install headlamp charts/headlamp`
- If you have anything in your default kubeconfig headlamp will pick it. Run the following command to access the cluster locally.

```bash
  export POD_NAME=$(kubectl get pods --namespace default -l "app.kubernetes.io/name=headlamp,app.kubernetes.io/instance=headlamp" -o jsonpath="{.items[0].metadata.name}")
  export CONTAINER_PORT=$(kubectl get pod --namespace default $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
  echo "Visit http://127.0.0.1:8080 to use your application"
  kubectl --namespace default port-forward $POD_NAME 8080:$CONTAINER_PORT
```

- Go to `http://localhost:8080/`
- Click on `New Cluster` button on the nav bar and paste your base64 encoded kubeconfig. I usually use https://www.base64encode.org/ to do it.
- I am pasting how my kubeconfig looks like

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: base64 data
    server: serverurl:port
  name: teststateless
contexts:
- context:
    cluster: teststateless
    user: clusterUser_knrt10-testing_knrt10
  name: teststateless
current-context: teststateless
kind: Config
preferences: {}
users:
- name: clusterUser_knrt10-testing_knrt10
  user:
    client-certificate-data: base64data
    client-key-data: base64data
    token: token
```

You can fill the values with your data and encode it from the above URL. I have tried it and everything seems to be working as expected. Please let me know if you have any questions. Thanks
