### ISSUE TITLE
cannot show ingresses in headlamp 0.25.0

### ISSUE THREAD

**Issue by intrand** [headlamp-k8s/headlamp#2261]
# Problem

When navigating to Network -> Ingresses, I'm greeted with an "Uh-oh! Something went wrong." Upon opening the console, I see more than a few of

```
vendor-mui-C3ciNw1R.js:39 TypeError: Cannot read properties of undefined (reading 'paths')
    at index-CCAjWvBk.js:849:42225
    at Array.forEach (<anonymous>)
    at Ai.getRules (index-CCAjWvBk.js:849:42185)
    at index-CCAjWvBk.js:1123:9724
    at Object.useMemo (vendor-mui-C3ciNw1R.js:37:58775)
    at He.useMemo (vendor-mui-C3ciNw1R.js:12:5905)
    at RulesDisplay (index-CCAjWvBk.js:1123:9701)
    at Wf (vendor-mui-C3ciNw1R.js:37:52830)
    at Rb (vendor-mui-C3ciNw1R.js:41:8734)
    at $b (vendor-mui-C3ciNw1R.js:41:950)
```

Which appears to me that `.spec.rules[].http` is coming back as null for some reason.

# Info

- Kubernetes 1.30.3
- Headlamp 0.25.0 / 06314eeb4ba7ea45d85441166fb9b696a0ac7a48
- A service account token bound to the ClusterRole `view`
- An `ingress` object which specifies `.spec.tls` for a wildcard subdomain
    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: wildcard
      namespace: ingressController
    spec:
      ingressClassName: whateverIngressClass
      rules:
        - host: '*.one.domain.tld'
        - host: '*.two.domain.tld'
      tls:
        - hosts:
            - '*.one.domain.tld'
            - '*.two.domain.tld'
          secretName: wildcard-cert
    ```

- `ingress` objects which don't specify `.spec.tls`
    ```yaml
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: headlamp
      namespace: headlamp
    spec:
      ingressClassName: whateverIngressClass
      rules:
      - host: headlamp.one.domain.tld
        http:
          paths:
          - backend:
              service:
                name: headlamp
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
      - host: headlamp.two.domain.tld
        http:
          paths:
          - backend:
              service:
                name: headlamp
                port:
                  number: 80
            path: /
            pathType: ImplementationSpecific
    ```
