### ISSUE TITLE
Unable to connect to GKE cluster from Desktop App

### ISSUE THREAD

**Issue by tblaisot** [headlamp-k8s/headlamp#2359]
Hello

I am unable to use headlamp to view my GKE cluster.
The probable cause is the auth method.
Since some years GCP have switched to auth using a gcloud plugin.
In my setup, the plugin is installed using gcloud: `gcloud components install gke-gcloud-auth-plugin` and i am able to connect to cluster without a problem using kubectl

this is the auth part of the kubeconfig for this cluster (generated using gcloud `gcloud container clusters get-credentials cluster`)
```yaml
users:
- name: redacted_cluster_name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin for use with kubectl by following
        https://cloud.google.com/kubernetes-engine/docs/how-to/cluster-access-for-kubectl#install_plugin
      provideClusterInfo: true
```
