### ISSUE TITLE
Regression (unreleased): Create dialog doesn't update cluster when it's changed

### ISSUE THREAD

**Issue by joaquimrocha** [headlamp-k8s/headlamp#2441]
**How to reproduce:**
1. From the Home view, go into cluster A; once it loads the cluster A overview, click the Home button again
2. From the Home view, go into cluster B; once it loads, click the Create button and add some resource there: e.g.
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  key1: value1
  key2: value2
```
3. Press apply; then press Cancel and close the dialog.
4. Use the **top cluster chooser**, choose cluster A again;
5. Click the Create button again, the resource **must still be there** (i.e. the whole view wasn't re-built); click apply.
6. Observe how it makes the request to apply into the previous cluster (cluster B).

This issue is related to the recent multi-cluster changes, because we get the list of clusters and assign the first one to a state. This state remains even when we change the cluster.
