### ISSUE TITLE
Helm Chart: storageClassName in PersistentVolumeClaim not applied, causing PVC to remain Pending

### ISSUE THREAD

**Issue by Heavybullets8** [headlamp-k8s/headlamp#2579]
## Describe the Bug
The Headlamp Helm chart does not apply the `storageClassName` specified in `values.yaml` for PersistentVolumeClaims (PVCs). This causes PVCs to remain in a `Pending` state in clusters without a default `StorageClass`, with the following error:

```
FailedBinding: no persistent volumes available for this claim and no storage class is set
```

---

## To Reproduce
Steps to reproduce the bug:
1. Ensure the cluster does **not** have a default `StorageClass`

2. Deploy the Headlamp Helm chart with the following `values.yaml`:
   ```yaml
   persistentVolumeClaim:
     enabled: true
     storageClassName:  <STORAGE_CLASS_NAME>
     accessModes:
       - ReadWriteOnce
     size: 1Gi
   ```
3. Check the PVC status:
   ```bash
   kubectl describe pvc -n <NAMESPACE> headlamp
   ```
   Error output:
   ```
   Events:
     Type    Reason         Age               From                         Message
     ----    ------         ----              ----                         -------
     Normal  FailedBinding  5s (x4 over 48s)  persistentvolume-controller  no persistent volumes available for this claim and no storage class is set
   ```

4. Verify the HelmRelease manifest:
   ```bash
   kubectl get helmrelease -n <NAMESPACE> headlamp -o yaml
   ```
   Output confirms the `storageClassName` is correctly set in the `values` field, but the rendered PVC still lacks it.

---

## Environment
- **Installation type**: In-Cluster (Helm chart)
- **Headlamp Version**: `0.26.0`
- **Kubernetes version**: `v1.31.2`
- **Other**:
  - Cluster does **not** have a default `StorageClass`.
  - Flux Helm Controller used for deployment.
  - Talos Linux: `v1.8.3`
  
---

## Additional Context
- The rendered PVC lacks the `storageClassName` despite it being correctly set in `values.yaml` and visible in the HelmRelease manifest. Example output:
   ```yaml
   StorageClass:
   Status: Pending
   ```
- The issue was resolved using a Flux post-renderer to patch the `storageClassName` dynamically. Example configuration:
   ```yaml         
     postRenderers:
       - kustomize:
           patches:
             - target:
                 version: v1
                 kind: PersistentVolumeClaim
                 name: headlamp
               patch: |
                 - op: add
                   path: /spec/storageClassName
                   value: openebs-hostpath
   ```

- This workaround forces the correct `storageClassName` into the PVC.

- Headlamp commits and everything I have tried is available on my Github repo via commit history on the file: https://github.com/Heavybullets8/heavy-ops/blob/main/kubernetes/apps/kube-system/headlamp/app/helmrelease.yaml
