### ISSUE TITLE
Pods are not displayed via the pods tab

### ISSUE THREAD

**Issue by fatsolko** [headlamp-k8s/headlamp#2598]
## Describe the bug
Log in to headlamp, go to the dex namespace in which I gave the user full access.
![image](https://github.com/user-attachments/assets/26b7565f-14ed-43ab-966a-c03d80d257e5)

```
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role
  namespace: dex
rules:
  - verbs:
      - '*'
    apiGroups:
      - '*'
    resources:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: developer
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role-binding
  namespace: dex
subjects:
  - kind: Group
    name: dex:infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: developer-role
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dex-developer
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: dex:infrastructure
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: developer


```

And I can get all the info if I navigate through the namespace tab through the resources.
![image](https://github.com/user-attachments/assets/3ec468b9-94dc-4ed2-b147-8daae684fd04)
But if I go to the pod\secret\etc tab, they will not be available.

If I go to the same in Lens with the same account, everything works as expected
![image](https://github.com/user-attachments/assets/c1124f27-5ea2-41c3-a32d-0766debaa36a)

I understand that the problem is most likely that headlamp first tries to get all the pods in the cluster (I did not give such permissions) and filter them on the frontend.
https://blabla.dev/c/main/pods?namespace=dex
And if you open the pod directly, then everything is ok
https://blabla.dev/c/main/pods/dex/dex-66c5fdc5b7-ng2bg

if I give `get list `permissions to pods in clusterRole, everything will work, but i don't want to give permissions to pods in whole cluster

## Environment:
 - Installation type: Helm
 - Headlamp Version: 1.27.5

## Are you able to fix this issue?
 No
