### ISSUE TITLE
Headlamp Cannot Access Dex via Public URL

### ISSUE THREAD

**Issue by yildizozan** [headlamp-k8s/headlamp#2625]
## Describe the bug
I installed Headlamp and Dex using Helm in a Kubernetes environment. My goal is to integrate LDAP and enable LDAP login similar to ArgoCD. While Headlamp accesses Dex through the address `headlamp.dashboard.svc.cluster.local`, Dex cannot respond back to this address, so the process cannot be completed. How can I make Headlamp access Dex through a public URL (https://dashboard.company.com) ? 

Note: This cannot be resolved with Dex redirectURIs.

## To Reproduce

Headlamp Helm Values
```yaml
config:
  oidc:
    clientID: headlamp
    clientSecret: 86cf07f5-a3f4-4401-9ad1-7e7dc9cbdae6
    issuerURL: https://dex.company.com
    scopes: "email"

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - host: dashboard.company.com
      paths:
      - path: /
        type: Prefix
```

Dex Helm Values
```
config:
  issuer: https://dex.company.com
  storage:
    type: kubernetes
    config:
      inCluster: true
  logger:
    level: debug
  staticClients:
    - id: headlamp
      name: 'Headlamp'
      redirectURIs:
        - https://dashboard.company.com/oidc-callback
      secret: t0pS3cr3t
  connectors:
  - id: ldap
    name: Company
    type: ldap
    config:
      bindDN: serviceuser@company.com
      bindPW: "XXXXX"
      groupSearch:
        baseDN: OU=XXXX,DC=company,DC=com
        filter: ""
        nameAttr: name
        userMatchers:
        - groupAttr: member
          userAttr: dn
      host: 10.0.0.1:389
      insecureNoSSL: true
      insecureSkipVerify: true
      userSearch:
        baseDN: OU=XXXX,DC=company,DC=com
        emailAttr: mail
        filter: ""
        idAttr: employeeNumber
        nameAttr: name
        preferredUsernameAttr: sAMAccountName
        username: sAMAccountName
      usernamePrompt: Username
```

If I enter my username password Dex not access `headlamp.dashboard.svc.cluster.local` 

## Environment (please provide info about your environment):
 - Installation type: Container-Image/In-Cluster/Helm
 - Kubernetes Version: v1.27.6
 - Headlamp Helm Chart 0.26.0
 - Dex Helm Chart 0.19.1

## Are you able to fix this issue?
Maybe
> Do you want to help fix this issue? Please see our [contribution docs](https://headlamp.dev/docs/latest/contributing). For any non-trivial contributions, we advise you to join our [our slack channel](https://kubernetes.slack.com/messages/headlamp) to discuss the implementation with Headlamp's core developers.

## Additional Context

Result
![Screenshot from 2024-11-30 00-22-12](https://github.com/user-attachments/assets/0681842f-ed8b-4286-9333-ba92afc78a9c)
