### ISSUE TITLE
Headlamp does not show restart/edit/scale buttons on resources with sufficient permissions

### ISSUE THREAD

**Issue by Andrew1988123123** [headlamp-k8s/headlamp#2633]
## Describe the bug
The bug title says it all. I gave permissions to restart, scale, edit the deployment but the button with the option to restart and scale the deployment does not appear. These are sufficient permissions because I tested using kubectl.
**kubectl rollout restart deployment gotify -n default**

According to the documentation the buttons should appear
https://headlamp.dev/docs/latest/faq/#headlamp-is-not-showing-deleteeditscale-buttons-in-a-resource-why-is-that

## To Reproduce
Create Deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gotify
  namespace: default
spec:
  selector:
    matchLabels:
      app: gotify
  replicas: 1
  template:
    metadata:
      labels:
        app: gotify
    spec:
      containers:
        - name: gotify
          image: gotify/server
          env:
            - name: GOTIFY_SERVER_PORT
              value: "81"
          ports:
            - containerPort: 81
          readinessProbe:
            httpGet:
              path: /health
              port: 81
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 81
            initialDelaySeconds: 10
            periodSeconds: 20
```
Create SA with secret
```
apiVersion: v1
kind: Secret
metadata:
  name: cluster-developer
  namespace: default
  annotations:
    kubernetes.io/service-account.name: cluster-developer
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-developer
  namespace: default
```
Create custom RBAC with sufficient permissions.
```apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-role
rules:
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/portforward" ]
    verbs: [ "get", "create", "delete" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "get", "create" ]
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "get" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments/scale" ]
    verbs: [ "get", "patch" ]
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "get", "patch" ]

---

# ClusterRoleBinding for granting the custom-role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-developer-binding
subjects:
  - kind: ServiceAccount
    name: cluster-developer
    namespace: default
roleRef:
  kind: ClusterRole
  name: custom-role
  apiGroup: rbac.authorization.k8s.io

---

# ClusterRoleBinding for granting the 'view' role to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-developer-view-binding
subjects:
  - kind: ServiceAccount
    name: cluster-developer
    namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
```

## Environment (please provide info about your environment):
 - Installation type: Windows-Winget
 - Headlamp Version: v0.26.0

## Are you able to fix this issue?
No. I work as devops :(

## Additional Context
![image](https://github.com/user-attachments/assets/54b2222e-dc8e-47b4-8e12-3a8f14f72458)

Excepted result
![image](https://github.com/user-attachments/assets/09fe3173-4d21-4350-b0e2-59c0a819ee9b)

Additionally, after pressing the actions button the bubble has weird formatting.
![image](https://github.com/user-attachments/assets/e4d4eb2c-55b8-426a-bed4-42dcf85f6c78)
