### ISSUE TITLE
Headlamp OIDC with GKE

### ISSUE THREAD

**Issue by slitsevych** [headlamp-k8s/headlamp#2643]
After numerous and various attempts it does not seem that Headlamp OIDC is working with GKE Identity Service and the only way to login is to use service account token. 

1. Enabled Identity Service with GKE (https://cloud.google.com/kubernetes-engine/docs/how-to/oidc)
2. Changed default ClientConfig to the following 
```
apiVersion: authentication.gke.io/v2alpha1
kind: ClientConfig
metadata:
  name: default
  namespace: kube-public
spec:
  authentication:
  - name: oidc
    oidc:
      clientID: <<MY_REALM/CLIENT_ID>>
      groupPrefix: 'oidc:'
      groupsClaim: groups
      issuerURI: https://<<KEYCLOACK_URL/realms/<<MY_REALM/CLIENT_ID>>
      kubectlRedirectURI: http://localhost:8000/callback
      scopes: email,profile
      userClaim: email
      userPrefix: 'oidc:'
  certificateAuthorityData: <<certificateAuthorityData>>
  internalServer: ""
  name: <<CLUSTER_NAME>>
  server: https://<<IP_ADDRESS_OF_gke-oidc-envoy LB service>>:443
  ```
  
  server is set to the IP address of the **gke-oidc-envoy** LB service in "**_anthos-identity-service_**" namespace
  
 3. Default login through `kubectl oidc login --login-config=client-config.yaml --cluster=<<CLUSTER_NAME>>` 
 where **client-config.yaml** is the same client configuration as shown above + clientSecret - **_works just fine_**. 
 I'm able to login with email that's mapped to "oidc:<<MY_EMAIL>>" and with clusterRoleBinding in place I'm able to gain the access.
 
 4. In Headlamp though, using the following config: 
 ```
    clientID: <<MY_REALM/CLIENT_ID>>
    clientSecret: <<CLIENT_SECRET>>
    issuerURL: https://<<KEYCLOACK_URL/realms/<<MY_REALM/CLIENT_ID>>
    scopes: email,profile
```

I cannot get any permissions/access. Moreover I don't see any relevant logs in headlamp at all, only messages like 
""_**events is forbidden: User \"system:anonymous\" cannot list resource \"events\" in API group \"\" at the cluster scope**_" appearing in the browser console

---
As such I have a couple of questions:
1. Is there any working example of Headlamp OIDC with GKE (if any) or is it broken at this point and awaiting a fix?
2. Is it possible to see/enable some debug logs of Headlamp OIDC flow with API server or at least any hints on that matter in logs?

---
And on a somewhat unrelated note, is there a way to suppress error message 
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":757,"error":"expiry time not found or invalid","time":"2024-12-06T07:41:50Z","message":"failed to get expiry time"}
when using service token without expiry?

**Comment by joaquimrocha** [comment]
cc/ @ashu8912

**Comment by imacq** [comment]
I have been facing this issue, any solution?

https://github.com/headlamp-k8s/headlamp/discussions/3036

**Comment by BenTheElder** [comment]
I suspect this is the same as https://github.com/kubernetes-sigs/headlamp/issues/266#issuecomment-2842359584

**Comment by illume** [comment]
GKE with OIDC (GKE Identity Service) is broken currently.

However, GKE Identity Service uses access_token. So I expect a new PR merged recently into main branch will help with this:
- https://github.com/kubernetes-sigs/headlamp/pull/3177


---


There are some new flags to use access_token rather than id_token.

Note, the values for the flags below are Untested for GKE Identity Service...
```
-oidc-validator-client-id=YOUR-GOOGLE-WORKFORCE-CLIENT-ID
-oidc-validator-idp-issuer-url=https://accounts.google.com
-oidc-use-access-token
```

Some existing flags may apply to GKE Identity Service
```
-oidc-username-claim=email
-oidc-groups-claim=groups
```

**Comment by mgalesloot** [comment]
I have a working setup with accounts.google.com, providing an oidc secret to headlamp helm chart with: 
```
OIDC_CLIENT_ID=<redacted> 
OIDC_CLIENT_SECRET=<redacted> 
OIDC_ISSUER_URL='https://accounts.google.com'
OIDC_SCOPES='email,profile'
```
This config works fine in headlamp already for quite some time. In the helm chart I do not specify command line args for headlamp, so we are using the defaults. 

In Headlamp v0.31 this config is broken. The env vars for OIDC_VALIDATOR are now required. I was able to fix this by adding to the helm chart: 
```
env:
    - name: OIDC_VALIDATOR_CLIENT_ID
      value: $(OIDC_CLIENT_ID)
    - name: OIDC_VALIDATOR_ISSUER_URL
      value: $(OIDC_ISSUER_URL)
```
