### ISSUE TITLE
EKS ? yes

### ISSUE THREAD

**Issue by bciceron** [headlamp-k8s/headlamp#266]
works like a charm on 2 clusters i tried.
using Version 0.3.0 (0.3.0) :)
much faster than Lens

**Comment by rbudiharso** [comment]
How to authenticate with eks? it ask for token, while Lens can do without asking for a token.

**Comment by joebowbeer** [comment]
The inability to easily use kubeconfig w/EKS AWS_PROFILE is a showstopper for us (unlike Octant, Lens, OpenLens, Aptakube, etc.)

**Comment by goutham-sabapathy** [comment]
So whats the solution for this ?? how do I connect to the clusters which are listed in my kube config file ?

**Comment by pmcdonald-metropolis** [comment]
bump

**Comment by mo-saeed** [comment]
is there anybody who was able to access EKS cluster using the token generated from [aws eks get-token](https://docs.aws.amazon.com/cli/latest/reference/eks/get-token.html)

**Comment by joebowbeer** [comment]
When the aws CLI adds a cluster to my kubeconfig, it adds an eks get-token command exec to the config.

Headlamp reads the kubeconfig and lists the cluster.

However, when I try to connect then headlamp asks me for a token. This is odd because the command to fetch a token is right there in the kubeconfig. Furthermore, since the eks get-token expires relatively quickly, there's no use in me entering a token manually. (Furthermore, Lens and Octant work as I expect.)

**Comment by joaquimrocha** [comment]
FTR, in the case of @joebowbeer this has to do with running when kubeconfig is set to use the exec plugin for getting the token from `aws`. We do need to make sure Headlamp is playing well with this.

**Comment by joaquimrocha** [comment]
Hi @joaocc , what version and flavor of Headlamp are you using? (Mac/Linux/Windows)

**Comment by joaocc** [comment]
Desktop-wise I am having issues with macOS and latest headlam.
We are also having some issues on k8s deployment (via helm) with keycloak SSO and multicluster (but it may be keycloak specific, not sure yet)

**Comment by joaocc** [comment]
Hi. Any updates on this? Thanks

**Comment by gabrielpetry** [comment]
It worked for me in aws eks using the AppImage version, the flatpak one didn't worked, probably it's due to how flatpak containers work ;(

**Comment by aviau** [comment]
Same issue here, its asking me for the token instead of running the command itself. I am on macOS

**Comment by joebowbeer** [comment]
I suggest closing this in favor of one of the newer issues. 

This was fixed for me in #1582

Also related are #1885 and #2255 

Please provide more details as well, such as the relevant contents of your kubeconfig

**Comment by aviau** [comment]
This is my kube_config:
```
apiVersion: v1
kind: Config
clusters:
  - name: arn:aws:eks:us-east-1:censored
    cluster:
      server: https://censored.gr7.us-east-1.eks.amazonaws.com
      certificate-authority-data: censored=
contexts:
  - name: arn:aws:eks:us-east-1:censored
    context:
      cluster: arn:aws:eks:us-east-1:censored
      user: arn:aws:eks:us-east-1:censored
users:
  - name: arn:aws:eks:us-east-1:censored
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1
        interactiveMode: IfAvailable
        command: aws
        args:
          - "--profile=censored"
          - "eks"
          - "get-token"
          - "--cluster-name=censored"
```

I am on `Version 0.29.0`


When I point to my kubeconfig, it then asks me for a token instead of using the exec command to get it.

I can somehow get it working by manually putting my config in `/Users/alexandre.viau/Library/Application\ Support/Headlamp/kubeconfigs/config`

**Comment by joebowbeer** [comment]
@aviau headlamp is able to parse you kubeconfig but it is not able to find it?

**Comment by schwichti** [comment]
I am using headlamp 0.29.0 on windows can cannot use it with a kubeconfig generated by `aws eks update-kubeconfig` (aws-cli/2.25.4 Python/3.12.9 Windows/11 exe/AMD64). I cannot even delete the cluster from the list of all clusters.

**Comment by stevehipwell** [comment]
This is still an issue on the latest Windows build, I can't connect to EKS or AKS using an exec plugin.

**Comment by joaocc** [comment]
Confirming this issue still happens on 0.30.0, macOS

**Comment by muhammad-asn** [comment]
> Confirming this issue still happens on 0.30.0, macOS

Use this instead, it works when passing the args inline
https://github.com/kubernetes-sigs/headlamp/issues/1582#issuecomment-2739659337

**Comment by joaocc** [comment]
Thanks! 
I missed that part of the explanation.
For future reference, moving profile from ENV to CLI works
``` 
users:
...
- name: arn:aws:eks:eu-west-1:000000000000:cluster/my-eks-cluster-01
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - my-eks-cluster-01
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: my-profile
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
``` 
users:
...
- name: arn:aws:eks:eu-west-1:000000000000:cluster/my-eks-cluster-01
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --profile
      - my-profile
      - --cluster-name
      - my-eks-cluster-01
      - --output
      - json
      command: aws
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

However, since AWS_PROFILE seems to be a pretty common way to pass that information (and seems to be the default when importing via aws-cli), is there any request to parse `AWS_PROFILE` and convert to `--profile`?
I have the impression that this is turning away a lot of potential users away.
Thanks
