### ISSUE TITLE
Pod restarting when using -base-url flag

### ISSUE THREAD

**Issue by bengivre** [headlamp-k8s/headlamp#2698]
## Describe the bug
Using the YML file :  https://raw.githubusercontent.com/headlamp-k8s/headlamp/main/kubernetes-headlamp.yaml
Just adding this the following arg:           **- "-base-url=/headlamp"**
The pod keep restarting 

Error log: 

```
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":339,"time":"2024-12-16T18:15:30Z","message":"Creating Headlamp handler"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":340,"time":"2024-12-16T18:15:30Z","message":"Kubeconfig path: "}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":341,"time":"2024-12-16T18:15:30Z","message":"Static plugin dir: /headlamp/static-plugins"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":342,"time":"2024-12-16T18:15:30Z","message":"Plugins dir: /headlamp/plugins"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":343,"time":"2024-12-16T18:15:30Z","message":"Dynamic clusters support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":344,"time":"2024-12-16T18:15:30Z","message":"Helm support: false"}
{"level":"info","source":"/headlamp/backend/cmd/headlamp.go","line":345,"time":"2024-12-16T18:15:30Z","message":"Proxy URLs: []"}
{"level":"info","context":"main","clusterURL":"https://10.43.0.1:443","source":"/headlamp/backend/pkg/kubeconfig/kubeconfig.go","line":267,"time":"2024-12-16T18:15:30Z","message":"Proxy setup"}
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":399,"error":"error loading kubeconfig files: error reading kubeconfig file: open : no such file or directory","time":"2024-12-16T18:15:30Z","message":"loading kubeconfig"}
*** Headlamp Server ***
  API Routers:
{"level":"error","source":"/headlamp/backend/cmd/headlamp.go","line":410,"error":"error loading kubeconfig files: error reading kubeconfig file: open /home/headlamp/.config/Headlamp/kubeconfigs/config: no such file or directory","time":"2024-12-16T18:15:30Z","message":"loading dynamic kubeconfig"}
```

**Relevant part of the yaml file modified :** 

```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:latest
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
          - "-base-url=/headlamp"
        ports:
        - containerPort: 4466
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
      nodeSelector:
        'kubernetes.io/os': linux

```
## To Reproduce
Steps to reproduce the bug:
1.  Download : https://raw.githubusercontent.com/headlamp-k8s/headlamp/main/kubernetes-headlamp.yaml
2. Edit the file kubernetes-headlamp.yaml
3. Add the following args:   
   **- "-base-url=/headlamp"**
4. See the pods keep restarting 

## Environment (please provide info about your environment):
 - Installation type: k3s single node on linux (Ubuntu 24.04.1 LTS) 
 - Headlamp Version: latest

## Are you able to fix this issue?
NO

## Additional Context
If you reverse the change about base-url, the pod stop restarting and works as expected 

Maybe this is similar to : https://github.com/headlamp-k8s/headlamp/pull/2477 but not sure how I can fix it on my side?
I understand [0.28.0](https://github.com/headlamp-k8s/headlamp/milestone/31) should fix it ? But I wonder that can I do before next release. Thanks a lot

**Comment by bengivre** [comment]
The crash loop keeps happening even with configuration with a static kubeconfigs : 
But no more errors messages. 

```
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: headlamp
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: headlamp
  template:
    metadata:
      labels:
        k8s-app: headlamp
    spec:
      containers:
      - name: headlamp
        image: ghcr.io/headlamp-k8s/headlamp:latest
        imagePullPolicy: Always
        args:
          - "-in-cluster"
          - "-plugins-dir=/headlamp/plugins"
          - "-base-url=/headlamp"
          - "-kubeconfig=/home/headlamp/.config/Headlamp/kubeconfigs/config"
        ports:
        - containerPort: 4466
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /
            port: 4466
          initialDelaySeconds: 30
          timeoutSeconds: 30
        volumeMounts:
           - name: "headlamp-kubeconfig"
             mountPath: "/home/headlamp/.config/Headlamp/kubeconfigs/"
      volumes:
         - name: "headlamp-kubeconfig"
           secret:
             secretName: "kubeconfig-vc-crossplane-consumer"
             items:
             - key: config
               path: config
      nodeSelector:
        'kubernetes.io/os': linux

```

As soon as I remove the **-base-url** it stays running..
