### ISSUE TITLE
Issue with getting prometheus metric to work with built in Kubernetes view role

### ISSUE THREAD

**Issue by sarg3nt** [headlamp-k8s/headlamp#2782]
## Describe the bug
We are trying to get headlamp prometheus graphs working with the built in `view` role in Kubernetes.
We've extended the capabilities of the logged in view user with the following.

```yaml
rules:
- apiGroups:
  - '*'
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - '*'
  resources:
  - resourcequotas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com/v1
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.coreos.com/v1alpha1
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  - appprojects
  verbs:
  - get
  - list
  - watch
```

But this is not working.
We did something similar with the built in `admin` role and it works fine, so there's something we are missing that the `admin` role has that `user` does not and our above rules do not cover.

## Environment (please provide info about your environment):
 - Installation type: Linux k8s cluster 1.31
 - Headlamp Version: 0.27.0

## Are you able to fix this issue?
No

**Comment by joaquimrocha** [comment]
cc/ @yolossn

**Comment by yolossn** [comment]
There is a similar issue discussing the api rights that are required for the prometheus plugin. Can you take a look and see if that answers your question.
https://github.com/headlamp-k8s/plugins/issues/39

**Comment by sarg3nt** [comment]
@yolossn Ahh, yep that fixed it.  Sorry for not finding that close issue before posting.

In case someone finds this in the future the tl;dr; answer for us was to add.

```yaml
apiGroups: [""]
resources: ["pods/proxy"]
verbs: ["get","list","watch"]
```

Though it sounds like only `get` is needed we didn't see the harm it adding the others.
