### ISSUE TITLE
Headlamp is not refreshing version 0.280

### ISSUE THREAD

**Issue by sov-msaeed** [headlamp-k8s/headlamp#2805]
when I try to delete resource, it's deleted successfully but headlamp is not refreshing to show the new created pod. the pod is just an example. but it happens with all resources 

## Environment (please provide info about your environment):
 - Installation type: MAC ARM64 (I use macbook M3)
 - Headlamp Version: 0.28.0

## Are you able to fix this issue?
[Yes (I will propose a PR) / No.]
no

<img width="560" alt="Image" src="https://github.com/user-attachments/assets/bed785a6-7b18-4f8f-9d25-5c63079b55f6" />

**Comment by joaquimrocha** [comment]
@skoeva Can you take a look?

**Comment by skoeva** [comment]
Hi, would you be able to list out the steps to recreate this issue? If there's any specific configuration for your resource(s), any relevant YAML would be useful to see. Any other additional info you think might be helpful would be very much appreciated as well

**Comment by illume** [comment]
The steps to reproduce are here:
>when I try to delete resource, it's deleted successfully but headlamp is not refreshing to show the new created pod. the pod is just an example. but it happens with all resources

**Comment by sov-msaeed** [comment]
@joaquimrocha is there any update here ? did you try to test it and see if you can reproduce the issue ?

**Comment by joaquimrocha** [comment]
cc/ @skoeva

**Comment by skoeva** [comment]
Are you creating a pod with the "Create" button in the sidebar? Would be nice to know how you're creating/deleting resources, that's what I meant before. Sorry if that wasn't clear.

For example, I'm testing on v0.28.0, and using this deployment YAML in the creation dialog from the sidebar:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

I can create and delete it without any issues. I'm only seeing the console errors you're seeing because I have clusters in Headlamp that aren't actively running.
