### ISSUE TITLE
Can't log in to Headlamp using ADFS integration

### ISSUE THREAD

**Issue by alexclear** [headlamp-k8s/headlamp#2918]
## Describe the bug
Headlamp does not allow to sign in using ADFS integration

## To Reproduce
Steps to reproduce the bug:
1. Install Headlamp using a Helm chart:
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  releaseName: headlamp
  chart:
    spec:
      chart: headlamp
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: kube-system
  interval: 15m
  timeout: 5m
  values:
    config:
      oidc:
        clientID: xxxxxxxx-xxxx-xxxx-xxxxxxxxxxxx
        clientSecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        issuerURL: https://sso.company.com/adfs
        scopes: "openid,profile,email"
    persistentVolumeClaim:
      enabled: true
      size: 1G
      accessModes:
      - ReadWriteOnce
      storageClassName: ec-csi-hi-sc
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
      - host: lamp.${cluster_subdomain}
        paths:
        - path: /
          type: ImplementationSpecific
```
2. Click on "Sign in"
4. See "Lost connection to the cluster" error

## Environment (please provide info about your environment):
 - Installation type: Helm
 - Headlamp Version: v0.28.1

## Are you able to fix this issue?
Not sure
