### ISSUE TITLE
OIDC setup with keycloak and helm chart issue - No Permission even followed the helm chart

### ISSUE THREAD

**Issue by JalenMak6** [headlamp-k8s/headlamp#2969]
## Describe the bug
I was able to deploy OIDC with keycloak and have the authentication page when trying to login. However, once I login with my account in keycloak, I could not see anything but getting

You don't have permissions to view this resource
events is forbidden: User "system:anonymous" cannot list resource "events" in API group "" at the cluster scope

I have setup the serviceaccount in the helm values.yml, the values.yml is shown below.

```
config:
  oidc:
    clientID: "headlamp-dev"
    clientSecret: "ffffffffffffiHmaOIK7ql3h5"
    issuerURL: "https://broker.stg.id.keycloak.com/auth/realms/my-realm"
    scopes: "openid profile email"

serviceAccount:
  create: true# Create a new service account
  name: headlamp-sa
clusterRoleBinding:
  # -- Specified whether a cluster role binding should be created
  create: true
  # -- Set name of the Cluster Role with limited permissions from you cluster
  # for example - clusterRoleName: user-ro
  clusterRoleName: cluster-admin


ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
  hosts:
    - host: headlamp.dev-k8s.mycluster.abc.com
      paths:
        - path: /
          type: ImplementationSpecific
  tls:
    - secretName: my-wildcard-cert
      hosts:
        - headlamp.dev-k8s.mycluster.abc.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
```

## Environment (please provide info about your environment):
 - Kubernetes v1.32.2
 - Headlamp Version:  latest, 0.20.1

## Are you able to fix this issue?
No

**Comment by sule26** [comment]
@JalenMak6 Were you able to solve it?

**Comment by illume** [comment]
Hi @JalenMak6 @sule26 

I know we're late with responding, apologies if this is stale for you now. 

I'd like to help try and debug this, let me know if it's still relevant to you?

There's been a number of OIDC related fixes in headlamp and in the docs in the last months, so it might be worth looking again. But people have been using KeyCloak with Headlamp for quite some years now, and I'm not aware that any of those fixes applied to KeyCloak and headlamp exactly. It might be worth asking on our slack, where there are more KeyCloak users than reading this github https://kubernetes.slack.com/messages/headlamp There's also some older KeyCloak related threads there that might give some clues.


---

- User "system:anonymous" is the default identity used by Kubernetes when a request is made without a valid authentication token.
-  I see you're using https and Traefik. You need to make sure your ingress or proxy forwards the X-Forwarded-Proto header to Headlamp. So that headlamp calls a https callback URL rather than a http one. I understand Traefik should send this header by default, but it's possible you may need to check your configuration.
- Is there a ClusterRoleBinding for that user? See https://headlamp.dev/docs/latest/installation/in-cluster/keycloak/#configuring-a-clusterrole-binding-for-the-oidc-user

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-clusterrolebinding
subjects:
  - kind: User
    name: <USER-EMAIL> # Please note that the name is case-sensitive
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cluster-admin # Specify the name of the ClusterRole to be bound
  apiGroup: rbac.authorization.k8s.io
```

- I wonder is it working with kubectl? See the section "Configuring kubectl for OIDC User Authentication" here: https://headlamp.dev/docs/latest/installation/in-cluster/keycloak/#configuring-a-clusterrole-binding-for-the-oidc-user
- I would check the oidc-callback inside KeyCloak is correct. If you are running Headlamp locally it should something like: `http://localhost:4466/oidc-callback` (but if you've deployed headlamp elsewhere it shouldn't be localhost of course). Check that URL is reachable from your browser too.
