### ISSUE TITLE
Support proxy-url in kubeconfig

### ISSUE THREAD

**Issue by gberche-orange** [headlamp-k8s/headlamp#916]
## Expected behavior

Given a desktop [headlamp](https://github.com/headlamp-k8s/headlamp) install on ubuntu using `flatpak run io.kinvolk.Headlamp`

Given a kubeconfig with a  `proxy-url` field as documented into https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/#proxy
When using headlamp to choose a cluster
Then the cluster has automatically its proxy settings filled in

```yaml
apiVersion: v1
kind: Config

clusters:
- cluster:
    proxy-url: http://proxy.example.org:3128
    server: https://k8s.example.org/k8s/clusters/c-xxyyzz
  name: development

users:
- name: developer

contexts:
- context:
  name: development
```

## observed behavior

The proxy-url is likely unused

See screenshot below
![image](https://user-images.githubusercontent.com/4748380/214335378-8846aaf9-f636-4189-8121-1153a4b05cce.png)

where as `kubectl get ns` command in the local desktop

## additional details 

<html>
<body>

Version | 0.14.1
-- | --
4420b0b06a82c373510ae6c0feae8584b9f47d33

</body>
</html>
